application: optimizely-chartio-embed
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

# site root
- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
